version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # yes `pip` also means `poetry`: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
