# Generated by Django 3.1.3 on 2020-11-05 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_auto_20201104_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="not_before",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Not published before this date",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="identifier",
            field=models.CharField(
                default=None,
                help_text="Well-known (external) identifier (e.g. CVE number)",
                max_length=32,
                unique=True,
            ),
        ),
    ]
