# Generated by Django 3.1.3 on 2020-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_auto_20201105_2147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ("identifier",)},
        ),
    ]
