# Generated by Django 3.1.3 on 2020-11-10 20:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_auto_20201110_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalIssue",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        default=None,
                        help_text="Well-known (external) identifier (e.g. CVE number)",
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description for this issue"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="A note regarding this issue"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical issue",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
