# Generated by Django 3.1.3 on 2020-11-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_auto_20201111_0055"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "unknown"),
                    ("AFFECTED", "affected"),
                    ("NOTAFFECTED", "notaffected"),
                    ("NOTFORUS", "notforus"),
                    ("WONTFIX", "wontfix"),
                ],
                default="UNKNOWN",
                help_text="The status the issue is currently in",
                max_length=11,
            ),
        ),
    ]
