# Generated by Django 3.1.3 on 2020-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_issuereference"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="status_reason",
            field=models.CharField(
                blank=True,
                help_text="A short explanation for the status",
                max_length=256,
            ),
        ),
    ]
