# Generated by Django 3.2.3 on 2021-05-14 15:57

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_issue_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("git_revision", models.CharField(max_length=64)),
                ("datetime_created", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageAttributeName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackageName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PackageVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="packageversion",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["value"], name="tracker_pac_value_fa8a51_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="packagename",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["value"], name="tracker_pac_value_8eef10_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="packageattributename",
            index=django.contrib.postgres.indexes.HashIndex(
                fields=["value"], name="tracker_pac_value_dbd288_hash"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="attribute_name_row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="tracker.packageattributename",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="channel_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="tracker.channelrevision",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="name_row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="tracker.packagename",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="version_row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="tracker.packageversion",
            ),
        ),
        migrations.AddField(
            model_name="channelrevision",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="tracker.channel",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["channel_revision", "attribute_name_row"],
                name="tracker_pac_channel_0205a2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("attribute_name_row", "channel_revision")},
        ),
        migrations.AlterUniqueTogether(
            name="channelrevision",
            unique_together={("name", "channel"), ("git_revision", "channel")},
        ),
    ]
