on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v4
      - uses: nixbuild/nixbuild-action@v1
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - run: nix-shell --pure --run pytest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v4
      - uses: nixbuild/nixbuild-action@v1
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - run: nix-build
      - run: nix-build -A staticFiles
      - run: nix-build -A manage
  instantiate-vm-test:
    # only instantiate but do not run/build the test as there is currently no way to use
    # KVM on neither GitHub Actions nor nixbuild.net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v4
      - uses: nixbuild/nixbuild-action@v1
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - run: nix-instantiate test.nix -A driver
